/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GameController;
import Model.PartieDeDefJam;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author p1508674
 */
public class GameView extends javax.swing.JFrame implements Observer{

    private ArrayList<JPanel> listPanel = new ArrayList<>();
    private JPanel tabJPanel[][];
    private PartieDeDefJam game ;
    private GameController gc;
    public ArrayList<JPanel> getTabPanels(){
        return this.listPanel;
    }
    /**
     * Creates new form GameView
     */
    public GameView(){
        
    }
    public GameView(GameController gc) {
       this.gc=gc;
       tabJPanel = new JPanel[6][4];
       initComponents();
       jPanel1.setLayout(new BorderLayout());
       
        /*this.pack();
        GameView.setDefaultLookAndFeelDecorated(true);
        this.setExtendedState(GameView.MAXIMIZED_BOTH);*/
       
       GridLayout gl = new GridLayout(6,4);
       
       
       JPanel gridContainer = new JPanel();
       gridContainer.setVisible(true);
       gridContainer.setLayout(gl);
     
       int j=0;
       int x=0;
       for(int i = 0 ; i < 24 ; i++){
           JPanel tmp = new JPanel();
            tmp.setBorder(BorderFactory.createLineBorder(Color.black));
            tmp.setLayout(new BorderLayout());
           listPanel.add(tmp);
           tabJPanel[x][j]=tmp;
           if(j==3){
               j=0;
               x++;
           }
           else
               j++;
           
       }
       for(JPanel jp : listPanel){
           gridContainer.add(jp);
       }
       for (int i= 0 ; i<6 ; i++){
           for (int z = 0 ; z<4 ; z++){
               JLabel jl = new JLabel();
               jl.setText(i+"-"+z);
               //tabJPanel[i][z].add(jl);
           }
       }
       for (int i =0 ; i<4; i++){
           tabJPanel[5][i].add(gc.getMc().getVisuCard1().get(i));
           tabJPanel[0][i].add(gc.getMc().getVisuCard2().get(i));
       }
       
       
       jPanel1.add(gridContainer,BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nbTour = new javax.swing.JLabel();
        nextTour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 850));

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("TOUR :");

        nbTour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nbTour.setText("jLabel2");

        nextTour.setText("Next Turn");
        nextTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nbTour)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(nextTour)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nbTour)
                        .addGap(42, 42, 42)
                        .addComponent(nextTour))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextTourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameView().setVisible(true);
            }
        });
    }

    public JLabel getTour(){
        return this.nbTour;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nbTour;
    private javax.swing.JButton nextTour;
    // End of variables declaration//GEN-END:variables

    public void setGame(PartieDeDefJam game) {
        this.game = game;
    }

    public PartieDeDefJam getGame() {
        return game;
    }

    public JButton getNextTurn(){
        return nextTour;
    }
    
    
    @Override
    public void update(Observable o, Object arg) {
        nbTour.setText(String.valueOf(game.getTour()));
    }
}
